name: tezwal
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  tezster_dart: ^2.1.1
  flutter_webview_plugin: ^0.3.11
  flutter_inappwebview: ^4.0.0
  permission_handler: ^5.0.0
  flutter_downloader: ^1.4.4
  path_provider: ^1.6.5
  shared_preferences: ^0.5.8
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  qr_flutter: ^3.2.0
  animated_text_kit:
  flutter_dialogflow: ^0.1.3
  bubble:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner: ^1.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/kallu-oaal-773d7ea19b97.json
    - assets/images/

  fonts:
    - family: Fuggles-Regular
      fonts:
        - asset: fonts/Fuggles-Regular.ttf
        - asset: fonts/BreeSerif-Regular.ttf
